export const GET_ALL_ROOMTYPES = "GET_ALL_ROOMTYPES";
export const DELETE_ROOMTYPE = "DELETE_ROOMTYPE";
export const CREATE_ROOMTYPE = "CREATE_ROOMTYPE";
export const PUT_ROOMTYPE = "PUT_ROOMTYPE";
export const GET_ROOMTYPE = "GET_ROOMTYPE";
export const CLEAR_ROOMTYPE = "CLEAR_ROOMTYPE";
