export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CHANGE_EMPLOYEE_STATE = "CHANGE_EMPLOYEE_STATE";
export const PUT_EMPLOYEE = "PUT_EMPLOYEE";
