export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const PUT_RESERVATION = "PUT_RESERVATION";
