export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const GET_RESERVATION = "GET_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const PUT_RESERVATION = "PUT_RESERVATION";
export const CHECKIN_RESERVATION = "CHECKIN_RESERVATION";
export const CHECKOUT_RESERVATION = "CHECKOUT_RESERVATION";
