export default [
  {
    id: 1,
    nombre: "Juan Perez",
    email: "juan@example.com",
    genero: "masculino",
    idCard: 1,
    phoneNumber: "+1234567890",
    rol: "cliente",
    gender: "masculino",
    adress: "Calle 123, Ciudad ABC",
    photo_url: "https://example.com/juan.jpg",
  },
  {
    id: 2,
    nombre: "María García",
    email: "maria@example.com",
    genero: "femenino",
    idCard: 2,
    phoneNumber: "+1987654321",
    rol: "administrador",
    gender: "femenino",
    adress: "Avenida XYZ, Pueblo 456",
    photo_url: "https://example.com/maria.jpg",
  },
  {
    id: 3,
    nombre: "Carlos González",
    email: "carlos@example.com",
    genero: "masculino",
    idCard: 3,
    phoneNumber: "+1122334455",
    rol: "empleado",
    gender: "masculino",
    adress: "Apartamento 789, Calle ZZZ",
    photo_url: "https://example.com/carlos.jpg",
  },
  {
    id: 4,
    nombre: "Laura López",
    email: "laura@example.com",
    genero: "femenino",
    idCard: 4,
    phoneNumber: "+1555666777",
    rol: "cliente",
    gender: "femenino",
    adress: "Calle Principal 456, Ciudad XYZ",
    photo_url: "https://example.com/laura.jpg",
  },
  {
    id: 5,
    nombre: "Pedro Martinez",
    email: "pedro@example.com",
    genero: "masculino",
    idCard: 5,
    phoneNumber: "+1444333222",
    rol: "empleado",
    gender: "masculino",
    adress: "Calle ABC, Apartamento 123",
    photo_url: "https://example.com/pedro.jpg",
  },
];
