export default [
  {
    nombre: "Juan Perez",
    email: "juan@example.com",
    is_Active: true,
    genero: "masculino",
    telefono: "+1234567890",
  },
  {
    nombre: "María García",
    email: "maria@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1987654321",
  },
  {
    nombre: "Carlos González",
    email: "carlos@example.com",
    is_Active: false,
    genero: "masculino",
    telefono: "+1122334455",
  },
  {
    nombre: "Laura López",
    email: "laura@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1555666777",
  },
  {
    nombre: "Pedro Martinez",
    email: "pedro@example.com",
    is_Active: true,
    genero: "masculino",
    telefono: "+1444333222",
  },
  {
    nombre: "Ana Rodríguez",
    email: "ana@example.com",
    is_Active: false,
    genero: "femenino",
    telefono: "+1666777888",
  },
  {
    nombre: "Diego Hernández",
    email: "diego@example.com",
    is_Active: true,
    genero: "masculino",
    telefono: "+1777888999",
  },
  {
    nombre: "Sofía Pérez",
    email: "sofia@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1888999000",
  },
  {
    nombre: "Javier Gómez",
    email: "javier@example.com",
    is_Active: false,
    genero: "masculino",
    telefono: "+1999000111",
  },
  {
    nombre: "Elena Fernandez",
    email: "elena@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1222111333",
  },
  {
    nombre: "Luisa Sanchez",
    email: "luisa@example.com",
    is_Active: false,
    genero: "femenino",
    telefono: "+1333222444",
  },
  {
    nombre: "Miguel López",
    email: "miguel@example.com",
    is_Active: true,
    genero: "masculino",
    telefono: "+1444333555",
  },
  {
    nombre: "Rosa Martínez",
    email: "rosa@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1555444666",
  },
  {
    nombre: "Pablo Castro",
    email: "pablo@example.com",
    is_Active: false,
    genero: "masculino",
    telefono: "+1666555777",
  },
  {
    nombre: "Carmen Ruiz",
    email: "carmen@example.com",
    is_Active: true,
    genero: "femenino",
    telefono: "+1777666888",
  },
];
