export default [
  {
    id: 1,
    nombre: "Juan Perez",
    email: "juan@example.com",
    genero: "masculino",
    telefono: "+1234567890",
    is_Active: true,
  },
  {
    id: 2,
    nombre: "María García",
    email: "maria@example.com",
    genero: "femenino",
    telefono: "+1987654321",
    is_Active: false,
  },
  {
    id: 3,
    nombre: "Carlos González",
    email: "carlos@example.com",
    genero: "masculino",
    telefono: "+1122334455",
    is_Active: true,
  },
  {
    id: 4,
    nombre: "Laura López",
    email: "laura@example.com",
    genero: "femenino",
    telefono: "+1555666777",
    is_Active: true,
  },
  {
    id: 5,
    nombre: "Pedro Martinez",
    email: "pedro@example.com",
    genero: "masculino",
    telefono: "+1444333222",
    is_Active: false,
  },
  {
    id: 6,
    nombre: "Ana Rodríguez",
    email: "ana@example.com",
    genero: "femenino",
    telefono: "+1666777888",
    is_Active: true,
  },
  {
    id: 7,
    nombre: "Diego Hernández",
    email: "diego@example.com",
    genero: "masculino",
    telefono: "+1777888999",
    is_Active: false,
  },
  {
    id: 8,
    nombre: "Sofía Pérez",
    email: "sofia@example.com",
    genero: "femenino",
    telefono: "+1888999000",
    is_Active: true,
  },
  {
    id: 9,
    nombre: "Javier Gómez",
    email: "javier@example.com",
    genero: "masculino",
    telefono: "+1999000111",
    is_Active: false,
  },
  {
    id: 10,
    nombre: "Elena Fernandez",
    email: "elena@example.com",
    genero: "femenino",
    telefono: "+1222111333",
    is_Active: true,
  },
  {
    id: 11,
    nombre: "Luisa Sanchez",
    email: "luisa@example.com",
    genero: "femenino",
    telefono: "+1333222444",
    is_Active: true,
  },
  {
    id: 12,
    nombre: "Miguel López",
    email: "miguel@example.com",
    genero: "masculino",
    telefono: "+1444333555",
    is_Active: false,
  },
  {
    id: 13,
    nombre: "Rosa Martínez",
    email: "rosa@example.com",
    genero: "femenino",
    telefono: "+1555444666",
    is_Active: true,
  },
  {
    id: 14,
    nombre: "Pablo Castro",
    email: "pablo@example.com",
    genero: "masculino",
    telefono: "+1666555777",
    is_Active: false,
  },
  {
    id: 15,
    nombre: "Carmen Ruiz",
    email: "carmen@example.com",
    genero: "femenino",
    telefono: "+1777666888",
    is_Active: true,
  },
  {
    id: 16,
    nombre: "Daniel Hernández",
    email: "daniel@example.com",
    genero: "masculino",
    telefono: "+1888777999",
    is_Active: false,
  },
  {
    id: 17,
    nombre: "Lucía González",
    email: "lucia@example.com",
    genero: "femenino",
    telefono: "+1999888000",
    is_Active: true,
  },
  {
    id: 18,
    nombre: "Alejandro Martinez",
    email: "alejandro@example.com",
    genero: "masculino",
    telefono: "+1222999111",
    is_Active: false,
  },
  {
    id: 19,
    nombre: "Sara López",
    email: "sara@example.com",
    genero: "femenino",
    telefono: "+1333000222",
    is_Active: true,
  },
  {
    id: 20,
    nombre: "Rubén Sánchez",
    email: "ruben@example.com",
    genero: "masculino",
    telefono: "+1444111333",
    is_Active: true,
  },
  {
    id: 21,
    nombre: "Natalia García",
    email: "natalia@example.com",
    genero: "femenino",
    telefono: "+1555222444",
    is_Active: false,
  },
  {
    id: 22,
    nombre: "Jorge Rodríguez",
    email: "jorge@example.com",
    genero: "masculino",
    telefono: "+1666333555",
    is_Active: true,
  },
  {
    id: 23,
    nombre: "Cristina Pérez",
    email: "cristina@example.com",
    genero: "femenino",
    telefono: "+1777444666",
    is_Active: false,
  },
  {
    id: 24,
    nombre: "Marcos Martínez",
    email: "marcos@example.com",
    genero: "masculino",
    telefono: "+1888555777",
    is_Active: true,
  },
  {
    id: 25,
    nombre: "Eva Ruiz",
    email: "eva@example.com",
    genero: "femenino",
    telefono: "+1999666888",
    is_Active: true,
  },
  {
    id: 26,
    nombre: "José García",
    email: "jose@example.com",
    genero: "masculino",
    telefono: "+1222777999",
    is_Active: false,
  },
  {
    id: 27,
    nombre: "Marina Fernández",
    email: "marina@example.com",
    genero: "femenino",
    telefono: "+1333888000",
    is_Active: true,
  },
  {
    id: 28,
    nombre: "Antonio Sánchez",
    email: "antonio@example.com",
    genero: "masculino",
    telefono: "+1444999111",
    is_Active: false,
  },
  {
    id: 29,
    nombre: "Silvia López",
    email: "silvia@example.com",
    genero: "femenino",
    telefono: "+1555000222",
    is_Active: true,
  },
  {
    id: 30,
    nombre: "Francisco Gómez",
    email: "francisco@example.com",
    genero: "masculino",
    telefono: "+1666111333",
    is_Active: true,
  },
];
